### ISSUE TITLE
Possible incompatibility with new conda or pip versions

### ISSUE THREAD

**Issue by djhoese** [astropy/ci-helpers#365]
I'm not sure this is `ci-helpers` problem but I'm not sure where else to post this. I'm hoping someone here can give me ideas while I debug this. I have some jobs failing on Travis that are using `ci-helpers`: https://travis-ci.org/pytroll/pycoast/jobs/474676327

The `.travis.yml` file has not changed in the pull request for this job, but it is still failing during the conda installation step of `ci-helpers`:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.15
  - numpy=stable
Use "conda info <package>" to see the dependencies for each package.
```

And later it shows:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.15
  - numpy=stable
Use "conda info <package>" to see the dependencies for each package.
Installing the dependency numpy with conda was unsuccessful, using pip instead.
Invalid requirement: 'numpystable.*'
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 11), (line:1, col:12)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 253, in install_req_from_line
    req = Requirement(req)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8], e.msg
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'.*'": Expected stringEnd
```

Does anyone have ideas what could be going on here? Note I'm also using `conda-forge` packages and `CONDA_CHANNEL_PRIORITY='True'`.

**Comment by djhoese** [comment]
I'm restarting the travis job just to make sure it wasn't a fluke or something that has already been fixed.

**Comment by djhoese** [comment]
Setting `NUMPY_VERSION=1.15` fixes the issue, but I'm still not sure why `stable` isn't an acceptable version anymore. Ideas?

**Comment by bsipocz** [comment]
This is a known issue for a while (https://github.com/astropy/ci-helpers/issues/284), but I haven't got around to fix it yet.
Please do remove numpy from `CONDA_DEPENDENCIES`. `'stable'` should work then.

**Comment by djhoese** [comment]
That fixed it. Thanks. I've had this in almost all my projects I think for a long time and never had a problem. Good to know it is an easy workaround. Thanks again.
